@echo off
echo Starting Kwantum Institute Development Environment...
echo.

echo Step 1: Starting Django Backend Server...
cd backend
echo Activating virtual environment...
call venv\Scripts\activate
echo Running Django migrations...
python manage.py migrate
echo Starting Django server...
start "Django Backend" cmd /k "cd /d %CD% && venv\Scripts\activate && python manage.py runserver"

echo.
echo Step 2: Starting React Frontend Server...
cd ..\frontend
echo Installing frontend dependencies...
call npm install
echo Starting React development server...
start "React Frontend" cmd /k "cd /d %CD% && npm start"

echo.
echo Development servers are starting...
echo Backend will be available at: http://localhost:8000
echo Frontend will be available at: http://localhost:3000 (or http://localhost:5173)
echo.
echo Django Admin: http://localhost:8000/admin/
echo.
echo Press any key to exit this script...
pause > nul 