# Generated by Django 6.0.7 on 2026-08-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=512)),
                ('source_type', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('start_index', models.IntegerField(default=0)),
                ('end_index', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source_id', 'start_index'],
            },
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=512)),
                ('node_type', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ProvenanceEntry',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('target_id', models.CharField(max_length=128)),
                ('target_type', models.CharField(choices=[('node', 'Node'), ('edge', 'Edge')], max_length=16)),
                ('source_id', models.CharField(max_length=512)),
                ('source_span', models.CharField(blank=True, max_length=512)),
                ('content_hash', models.CharField(blank=True, max_length=128)),
                ('confidence', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, max_length=512)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='graphrag.graphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='graphrag.graphnode')),
            ],
            options={
                'ordering': ['source__label', 'edge_type', 'target__label'],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'edge_type'), name='unique_edge_type_per_pair')],
            },
        ),
    ]
