name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          npm run build
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add origin https://github.com/${GITHUB_REPO}.git
          git push --force origin main:gh-pages
